### ISSUE TITLE
node_modules not found on docker

### ISSUE THREAD

**Issue by tiagoaguiar31** [SamKirkland/FTP-Deploy-Action-Typescript#3]
Hi Sam,
It's more a question that maybe you could help me:
When deploying to Azure all files seems to transfer but node_modules.
Any idea on what can be happening?

Thanks!

**Comment by SamKirkland** [comment]
Thanks for the question. I tried my best to explain the situation, let me know if this doesn't answer the question and I can reopen the ticket.

---

By default this action only deploys what you've checked into github.
`node_modules` only exists after you've run `npm install` and doesn't exist in source control.
Good news, this is easy to fix!

You shouldn't be publishing `node_modules`, those files are only needed to build your project. Once you build the project you can publish the output files. `node_modules` can be hundreds of MB and would take a long time to upload, and your built code doesn't even use it!

To resolve your issue use the example below as a starting point, I've heavily commented the code to help you out.

```yaml
on: push
name: Build and Publish Front End Framework Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:

    # Get latest code from github
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    
    # Tell the action you'll be using node
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        
    # Run npm install (to get npm packages aka node_modules)
    # Run your build to get output (in this case I'm assuming you have "build" under "scripts" in your package.json file and it will output a folder with your built website)
    - name: Build Project
      run: |
        npm install
        npm run build --if-present
        
    # output a list of files at this point, useful for debugging
    - name: List output files
      run: ls
      
    # Publish output folder (in step 4 above it generates a `build/` folder with all the html/js/css I need)
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ftp.samkirkland.com
        FTP_USERNAME: myFTPUsername
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
        LOCAL_DIR: build
        ARGS: --delete
```
